### ISSUE TITLE
Bug arma Bebedora de Almas

### ISSUE THREAD

**Issue by joehce3002** [elerendon/Bugtracker-548#2]
buenas tardes señor mj, el arma tiene el bug de no reconocer como arma de una mano para la rama de proteccion del paladin en el poder de martillo del honrado, no se si solo es en mi pj o en los demas.
adjuntamos un video para que se pueda observar

https://user-images.githubusercontent.com/97065010/147984268-5f6cb31c-4d3c-4d25-9003-c1d6c235d89e.mp4

**Comment by elerendon** [comment]
esto se pandaria, este reporte va para cataclismo
