### ISSUE TITLE
Bug misiones

### ISSUE THREAD

**Issue by huk145** [elerendon/Bugtracker-548#3]
Las misiones necesarias para aprender el hechizo "Montar sobre un Dragón nimbo" están bug. La misión "Surcar los cielos" no aparece a pesar de tener todas la misiones completadas y la reputación necesaria. Dejo link de la misión http://es.wowhead.com/quest=31811/surcar-los-cielos

**Comment by elerendon** [comment]
no tenemos los datos necesarios para corregir esto
